"""Build the local personal base image used by project images."""

from __future__ import annotations

import subprocess
import tempfile
import os
from pathlib import Path

from carthage import EXPECTED_BASE_IMAGE_TAG, PERSONAL_BASE_IMAGE_REPO
from carthage.personal_config import PersonalConfig


def personal_image_ref(tag: str = EXPECTED_BASE_IMAGE_TAG) -> str:
    # Test hook: e2e tests isolate personal images from the user's real
    # carthage-base-personal tag and clean up the generated repo afterward.
    repo = os.environ.get("CARTHAGE_PERSONAL_IMAGE_REPO", PERSONAL_BASE_IMAGE_REPO)
    return f"{repo}:{tag}"


def render_personal_image_dockerfile(base_image: str, config: PersonalConfig) -> str:
    lines = [
        "# Generated by carthage fortify. Do not edit.",
        f"FROM {base_image}",
        "",
        "USER root",
    ]
    if config.image.apt_packages:
        lines.extend([
            "",
            "RUN apt-get update \\",
            " && apt-get install -y --no-install-recommends \\",
        ])
        for package in config.image.apt_packages:
            lines.append(f"      {package} \\")
        lines.append(" && rm -rf /var/lib/apt/lists/*")
    lines.extend([
        "",
        "USER carthage",
        "WORKDIR /workspace",
        "",
    ])
    return "\n".join(lines)


def build_personal_image(
    *,
    base_image: str,
    target_image: str,
    config: PersonalConfig,
) -> tuple[bool, str]:
    with tempfile.TemporaryDirectory(prefix="carthage-personal-image-") as tmp:
        dockerfile = Path(tmp) / "Dockerfile"
        dockerfile.write_text(render_personal_image_dockerfile(base_image, config))
        result = subprocess.run(
            ["docker", "build", "-t", target_image, "-f", str(dockerfile), tmp],
            capture_output=True,
            text=True,
        )
    if result.returncode != 0:
        tail = (result.stderr.strip() or result.stdout.strip()).splitlines()
        return False, tail[-1] if tail else f"docker build exited {result.returncode}"
    return True, target_image
